controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# HelloController4:
#     path: /bonjour/{number1}/{number2}
#     controller : App\Controller\HelloController::sayHelloParamNumber